version: '3'

services:
  postgres:
    image: postgres:13
    container_name: astro_postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow_db
    ports:
      - "5433:5432"  # cuidado pra não conflitar com outros PostgreSQL locais
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ibge_elt_project_default
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 10s
      timeout: 5s
      retries: 5
      
  scheduler:
    volumes:
      - ./include/.dbt:/usr/local/airflow/.dbt

volumes:
  postgres_data:


networks:
  ibge_elt_project_default:
    external: true
