version: 2

models:
  - name: fato_populacao
    columns:
      - name: id_estado
        tests:
          - not_null
      - name: nome_estado
        tests:
          - not_null
      - name: nivel_estado
        tests:
          - not_null
      - name: ano
        tests:
          - not_null
      - name: populacao
        tests:
          - not_null
