version: 2

models:
  - name: fato_populacao
    columns:
      - name: id_localidade
        tests:
          - not_null
      - name: nivel_localidade
        tests:
          - not_null
      - name: nome_localidade
        tests:
          - not_null
      - name: populacao_2014
        tests:
          - not_null
      - name: populacao_2015
        tests:
          - not_null
      - name: populacao_2016
        tests:
          - not_null
      - name: populacao_2017
        tests:
          - not_null
      - name: populacao_2018
        tests:
          - not_null
      - name: populacao_2019
        tests:
          - not_null
      - name: populacao_2020
        tests:
          - not_null
      - name: populacao_2021
        tests:
          - not_null
      - name: populacao_2024
        tests:
          - not_null