dbt_project:
  target: dev
  outputs:
    dev:
      type: postgres
      host: host.docker.internal
      port: 5434         
      user: dw_user
      password: dw_pass
      dbname: dw_database
      schema: public
      threads: 1
