dbt_project:
  target: dev
  outputs:
    dev:
      type: postgres
      host: host.docker.internal  
      user: dw_admin
      password: dw_pass
      port: 5434
      dbname: dw_database
      schema: public
      threads: 4
