version: 2

models:
  - name: dim_regiao
    columns:
      - name: id_regiao
        tests:
          - not_null
          - unique
      - name: sigla_regiao
        tests:
          - not_null
      - name: nome_regiao
        tests:
          - not_null

  - name: dim_estado
    columns:
      - name: id_estado
        tests:
          - not_null
          - unique
      - name: sigla_estado
        tests:
          - not_null
      - name: nome_estado
        tests:
          - not_null
      - name: id_regiao
        tests:
          - not_null
          - relationships:
              to: ref('dim_regiao')
              field: id_regiao

  - name: dim_intermediaria
    columns:
      - name: id_intermediaria
        tests:
          - not_null
          - unique
      - name: nome_intermediaria
        tests:
          - not_null
      - name: id_uf
        tests:
          - not_null
      - name: sigla_uf
        tests:
          - not_null

  - name: dim_imediata
    columns:
      - name: id_imediata
        tests:
          - not_null
          - unique
      - name: nome_imediata
        tests:
          - not_null
      - name: id_intermediaria
        tests:
          - not_null
          - relationships:
              to: ref('dim_intermediaria')
              field: id_intermediaria
      - name: sigla_uf
        tests:
          - not_null
      - name: nome_uf
        tests:
          - not_null

  - name: dim_municipio
    columns:
      - name: id_municipio
        tests:
          - not_null
          - relationships:
              to: ref('dim_municipio')
              field: id_municipio
      - name: nome_municipio
        tests:
          - not_null
      - name: id_microrregiao
        tests:
          - not_null
      - name: nome_microrregiao
        tests:
          - not_null
      - name: id_mesorregiao
        tests:
          - not_null
      - name: nome_mesorregiao
        tests:
          - not_null
      - name: id_uf
        tests:
          - not_null
      - name: sigla_uf
        tests:
          - not_null
      - name: nome_uf
        tests:
          - not_null

  - name: dim_distrito
    columns:
      - name: id_distrito
        tests:
          - not_null
          - unique
      - name: nome_distrito
        tests:
          - not_null
      - name: municipio_id
        tests:
          - not_null
          - relationships:
              to: ref('dim_municipio')
              field: id_municipio
      - name: nome_uf
        tests:
          - not_null

  - name: dim_subdistrito
    columns:
      - name: id_subdistrito
        tests:
          - not_null
          - unique
      - name: nome_subdistrito
        tests:
          - not_null
      - name: id_distrito
        tests:
          - not_null
          - relationships:
              to: ref('dim_distrito')
              field: id_distrito
      - name: nome_municipio
        tests:
          - not_null
