version: 2

sources:
  - name: raw
    database: dw_database
    schema: tmp_astro  
    tables:
      - name: regioes
      - name: populacao
      - name: estados
      - name: intermediarias
      - name: imediatas
      - name: municipios
      - name: distritos
      - name: subdistritos
